### PR TITLE
Changes for role updation of user

### PR DESCRIPTION
**Pull request by anitha181992**
@Chinmay-92 
@anut347 
This pull request is only for review for "Update Role api", so please dont merge it.
The changes include.
1)Database changes: Removing the primary key constraint on member_parent, since there is complexity in the composite IDs representation in JPA model and also the field is only for two values: **RegisteredUse**r and **UserAdmin**
2)about.html is just modified for the testing. I will revoke it back once reviewed

Issue link: https://github.com/ABenchM/abm/issues/166

### CODE REVIEW

**Comment by anut347** [comment]
@anitha181992 : For composite primary keys,  we can use sql delete queries and use execute query. I dont think we need to alter the DB.

**Comment by anitha181992** [comment]
@anut347 : The issue is with the datamodel representation , not with the queries.

**Comment by Chinmay-92** [comment]
Any update with this PR? @anitha181992 & @anut347 
What would be next steps?

**Comment by anitha181992** [comment]
Making changes as suggested, so creating new pull request and closing this one

**Pull request closed without merging**
