### PR TITLE
Changes for get all users

### PR DESCRIPTION
**Pull request by anut347**
Changes for get all users. Test Case will  be pushed by Chinmay in the next pull request which will also be created in sometime.

https://github.com/ABenchM/abm/issues/259

Changes in Files below:
UserDetailsController.java
JpaRoleMembers.java
JpaUser.java
JpaUserDao.java
UserDao.java
RoleMembersDTO.java
UserDTO.java

### CODE REVIEW

**Comment by anut347** [comment]
GetUsersControllerTest.java added by Chinmay in anu_getUsers_merge

**Comment by ankur-1989** [comment]
Hi, 

Review Comments are as follows - 

1. Is this pull request only for loading the users on Manage Users page and PendingList page or is there any other functionality that this pull request caters?
2. I am not getting a list of approved users on Manage users page - I set the approved to 1 in the database for a particular user. Do I need to set something apart from this?
3. Test case - "testApprovedUsers" is getting failed in GetUsersControlledTest with the following error 
           java.lang.AssertionError: expected:<true> but was:<false>
Reason might be, it is fetching a list of users with approved=0.

Best Regards,
Ankur Gupta

**Comment by ankur-1989** [comment]
Hi, 
Now I am able to get the list of users on both pages. We need data in role and role_members tables as well. 
One suggestion - 

Here in this image - change role button comes like a text so can be confusing for the user. It is better to show the down arrowhead along with it. 

image

Now both the test cases are failing. Maybe it is because of wrong conditions are given for approved in the test cases. It should be vice versa.

Best Regards,
Ankur

**Comment by anut347** [comment]
Taggind Vishal to keep track of the frontend change suggestion. @vishaljcj .

@Chinmay-92 :Please have a look at the test cases.

**Comment by Chinmay-92** [comment]
Test method is fixed 
@ankur-1989 please re-run the Tests and let me know

**Pull request merged**
