### PR TITLE
Get all public collections for admin/active collections

### PR DESCRIPTION
**Pull request by anitha181992**
a) To populate the "Manage Collections" for UserAdmin
-Changes are included in the method getCollections() in CollectionController.java
Test case: ManagePublicCollectionTest

b)To activate/deactivate Public collections
- We can activate/deactivate the public collections.
- The users will not be able to view deactivated public collections.

-Changes included:
New controller: ActiveCollectionController.java
Test case : ActivateCollectionControllerTest.java

Existing classes changed: JpaCollection.java
JpaCollectionDao.java
CollectionDao.java
CollectionDTO.java

Issues link: https://github.com/ABenchM/abm/issues/196
https://github.com/ABenchM/abm/issues/219

### CODE REVIEW

**Comment by anitha181992** [comment]
activatecollection

**Comment by anitha181992** [comment]
managepubliccollection

**Comment by anitha181992** [comment]
@ankur-1989 :Added the screenshots and the testcases for all the functionalities added

**Comment by ankur-1989** [comment]
Hi @anitha181992 ,
Can you please tell me the front end branch that i need to use for testing ?

**Comment by anitha181992** [comment]
Frontendpg- for the front end testing

**Comment by ankur-1989** [comment]
Hi @anitha181992 

When i am using frontendpg branch i am getting issues. When I click on demo user button in order to reach manage public collections options i get the following error - 
image
2.  I guess you are updating the column in the collections table, then you should name the method starting with put.
3. Is it the same PR when we were talking about if we could use this one method in the collection controller itself instead of writing a new controller? 
 
 Please have a look.

**Comment by anitha181992** [comment]
@vishaljcj 
@TalalE : Could you please look at the issue in the frontendpg.

@ankur-1989 : I have updated the method name and this is the same method code changes which was discussed to be done in the existing controller

**Comment by ankur-1989** [comment]
So can we use this method in the existing controller?

**Comment by anitha181992** [comment]
@ankur-1989 : i guess there is a bit of confusion here
This pull request has two functionalities added, while the previous pull request had only one functionality which is to populate manage collections page of admin, I had written a separate controller for that, but now I have incorporated the changes in the Collectioncontroller itself, the method name is findCollections() and removed the separate controller.
The other functionality where a new controller ActiveCollectionController is written is for Activate/Deactivate public collections, which is a new feature added to ABM. 
I hope this clarifies

**Comment by vishaljcj** [comment]
@ankur-1989 changes have been done for these issues in the frontendpg branch. This branch is still not in sync....structure-wise with the develop branch, but @TalalE will be raising a PR in the frontend for this 'Manage Public Collections' page probably by tomorrow. But just in case you want to perform the testing before that you can use the frontendpg branch. And as for the error that pops up in the public collections page, please make sure to add the new column 'isActive' to the collection table.

**Comment by ankur-1989** [comment]
@anitha181992 
Please include this method in the collection controller itself as if you see controllers are made components wise instead of functionalities wise. So it is better to include the method in the collection controller itself.

**Comment by anitha181992** [comment]
There is already a put() method in the collection controller class, as per my knowledge we can have only one put or get or post method in a single controller.

**Comment by ankur-1989** [comment]
I dont think this is the case. you can have multiple put methods in single controller, because name will be different. you can see in hermesController we have multiple post methods.

**Comment by Chinmay-92** [comment]
@anitha181992 you can add more than 1 method in a controller with different names
for example: UserController(in anu_deleteUserAndRenaming branch) has getUsername and getIsPasswordMatched methods both are GET

**Comment by anitha181992** [comment]
The pull request comments are addressed in https://github.com/ABenchM/abm/pull/303, so closing this one

**Comment by ankur-1989** [comment]
@anitha181992 
Please close this if you have opened the new one.

**Pull request closed without merging**
