### PR TITLE
Approve user for admin

### PR DESCRIPTION
**Pull request by anut347**
---
name: Pull request
about: Code to approve a user on approve button click. This is specific to admin users
---

**List of functionalities contained in this pull request**
- mail to user when admin approves
- approve user via pending requests page for admin

**List of the test cases**
Test case to approve user is included in the file UsedrInfoUpdateTest.java.

### CODE REVIEW

**Comment by ankur-1989** [comment]
@anut347 
Please attach the screenshot for passed test cases.
Thanks!!
Ankur

**Comment by anut347** [comment]
screenshot from 2018-12-20 17-14-00

**Comment by anut347** [comment]
screenshot from 2018-12-20 17-15-53

**Comment by anut347** [comment]
Test case : testApproveUser()
approved testUser1

**Comment by ankur-1989** [comment]
Hi, 

I am not able to run the test as the testapprove method does not approve the user. I am logged in with UserAdmin access. Did you test this in Uni domain?

image

image


Best Regards,
Ankur Gupta

**Comment by ankur-1989** [comment]
@anut347 
Any update on this ?

**Comment by anut347** [comment]
Hi Ankur
I did. And it works fine for me.

**Comment by anut347** [comment]
Hi Ankur... I deleted all test users and tried again. This time when i ran the test case for the first time it gave me this error and then when i ran it the second time it worked. Not sure why.

When we approve a user entry is made to the role_members table which is used in the getUserInfo.

Not sure why I'm not able to access it immediately.

**Comment by anut347** [comment]
I've moved the getUserInfoPart to another method testApprovedUserStatus(commented as of now).
Please check.

**Comment by ankur-1989** [comment]
Hi @anut347,
Can I test this pull request with develop front end branch ? if no, please let me know which branch should I use?
Best Regards,
Ankur Gupta

**Comment by anu347** [comment]
U can use the pg develop branch in frontend

**Comment by ankur-1989** [comment]
there is no pgdevelop branch. do you mean frontendpg ?

**Comment by anut347** [comment]
yes frontendpg. Sorry i forgot the name.

Tagging Vishal for the frontend comment.
@vishaljcj :FYI

**Comment by ankur-1989** [comment]
@anu347 

Using frontendpg branch and logged in with demo user who is user admin, but not able to see the pending request page. 
image
image

**Comment by ankur-1989** [comment]
on approving the user I am not getting mail as well on my gmail id.

**Comment by anut347** [comment]
Hi Ankur, I'll add the mail sending feature in another pull request. When i tried yesterday, we were able to send mails only to uni mail ids for this feature even though mail was getting sent to outside mail id for forgot password feature.

**Comment by ankur-1989** [comment]
thanks for the info. Please let me know once the frontend branch is fixed then i will check the pending page functionality.

**Comment by ankur-1989** [comment]
Hi @anu347 

I tried uni email id as well but did not get the email on approval. I tried the following things, let me know if I have missed something.

1. I ran the UserInfoControllerTest.java test case which consists of registering a user followed by approving the user and I am logged in with UserAdmin user.
2. I clicked on the activation link as well.

**Comment by anut347** [comment]
Hi Ankur,

I've commented out that mail sending method call as of now.

UserApprovalController.java
line no.92
sendApproveRejectEmail(username, true, userEmail);
which is commented as of now since I was facing issue with sending mail to outside mails.

I'll create another pull request for the sending mail for approve/reject feature. Else I can uncomment this and in that case only uni mails will be accepted for this feature as of now.

**Comment by vishaljcj** [comment]
@ankur-1989 you can use the abm-pen-req branch in the frontend for testing this. PR #258 has been raised for the same in abm-frontend, and you can test both these PRs simulataneously.

**Comment by anut347** [comment]
Hi Ankur, I've uncommented the approve mail sending code as well.

**Comment by anut347** [comment]
commented out the mail sending code again since it was not working for Ankur. Will handle the mail sending part as another pull request after the functionalities are checked in.

**Pull request merged**
