### PR TITLE
changes for user registration(enhancement)

### PR DESCRIPTION
**Pull request by anut347**
changes for user registration(enhancement) and clean up for getUsers test

### CODE REVIEW

**Comment by anut347** [comment]
Sure Ankur. @anitha181992 @Chinmay-92  : FYI

This pull request is for the user registration enhancement. We've added a few more fields in user table 
It also takes care of the user details update for the user profile page.

Test case is specific to user registration/update are in UserInfoControllerTest.java.
Also I've cleaned up code in GetUsersControllerTest.java.

File changes for backend functionality changes in the below files: 
UserController.java
JpaUserDao.java
UserDao.java


DB changes are alrerady added into abm.sql in the prev pull request.

I dont think we can create pull requestr for front end as well since we work separately. 
@nguyenLisa :Please provide your inpput on this.

**Comment by ankur-1989** [comment]
Hi,

So, what I could understand after looking into the code is 
1. As part of this request, we are adding new registration fields in database. But One thing which is missing there is no firstname and lastname field on Registration page and it is adding some random value in the database. It should not happen.
2. We can write one more test wrt to this database change - where we will test if the right values are getting updated in the database in respective tables. 
3. As you mentioned about, details update for user profile page - I did not get the real meaning of it 
For example -  
   Suppose if I send a registration request with all the details it will send the registration mail to the approver. Later I felt i have  filled the wrong details then I updated my correct details with the same username and submit it. So it does not send the request for approval to approver again. 
and if the case of update is through user profile page then I guess you have not provided the functionality yet to load the user data in user profile page in this pull request. 

4. Could you please write one more test case to test the update functionality instead of updating the detail manually in the given test case. 


BR, 
Ankur

**Comment by Chinmay-92** [comment]
@anut347 please push the code changes for loading user data in user profile page.
@ankur-1989 did you take latest pull from *frontendpg* branch, registration page is fixed where we can enter first name and last name. ( as of now, fname and lname are not mandatory so we are allowing null values to be sent )

hope this will help.

**Comment by ankur-1989** [comment]
Hi, 
That's why I suggested we should raise pull request (Backend + front end) combination as it completes one functionality. I'll pull the latest one.
BR,
Ankur

**Comment by ankur-1989** [comment]
Hi, 
New pull request brings new issues 
1. On opening a registration page, it gives me error alerts. 
2. It is the same case with the User Profile page.
3. I am keeping this PR on hold as of now, because, a couple of test cases need to be fixed and it has frontend dependency. 
BR,
Ankur

**Comment by Chinmay-92** [comment]
@vishaljcj tagging for frontend related changes for this PR

**Comment by vishaljcj** [comment]
@ankur-1989 1. changes for the registration page has been pushed to frontendpg branch.
2. Could you please send me the error screenshot...as I am not getting any error for the user profile page.

**Comment by ankur-1989** [comment]
image

**Comment by anut347** [comment]
I've pushed the code for User Profile page also i.e., method getUsername and dependencies along with test case in GetUserDetailsControllerTest.java

**Comment by ankur-1989** [comment]
Hi, 
Review Comments below:- 
1. User Registration is working fine. proper details are getting updated in the database.
2. Frontendpg branch still has errors in the loading of pages such as UserProfile etc, However, it is not part of this pull request.
3. As discussed, Could you please write one more test case to check if it has updated the database table correctly.

**Comment by ankur-1989** [comment]
Hi,
I meant to create test case to check the database table if User table has got the entries correctly. suppose if we don't give firstname and lastname then in database it should take null values instead of some random values.
Let me know if there is still any doubt.
Thanks and Regards,
Ankur

**Comment by Chinmay-92** [comment]
Hi @ankur-1989 

I have created new issue to write the test case for db null name user.
[https://github.com/ABenchM/abm/issues/267](url)

Since this is minor test case, could you approve this PR for now if everything else is working and anu will push test case once it's finished?

We have sequential PRs(7-8 more) to raise this week and all are pending until this one gets approved.

**Comment by nguyenLisa** [comment]
Hi @Chinmay-92 ,

Sorry, but we will not accept any PRs if they are not properly tested. This is especially important if your next PRs depend on this one. What if this introduces an issue for later?

**Comment by ankur-1989** [comment]
Hi,
when I am testing the test case written in this file "GetUserDetailsControllerTest.java ", It is giving me an  error.
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
Please have a look once.
Thanks and Regards,
Ankur Gupta

**Comment by anut347** [comment]
Hi Ankur, I just checked it and it is working fine for me. Its testing for demo user. I hope there is demo user in your DB. Please attach a screen shot of the error you're getting.

**Comment by ankur-1989** [comment]
Hi, 
Please find attached the screenshot.

image

**Pull request merged**
