### PR TITLE
getallcollectionchanges and activate/deactivate public collections

### PR DESCRIPTION
**Pull request by anitha181992**
a) To populate the "Manage Collections" for UserAdmin
-Changes are included in the method getCollections() in CollectionController.java
Test case: ManagePublicCollectionTest

b)To activate/deactivate Public collections

    We can activate/deactivate the public collections.
    The users will not be able to view deactivated public collections.

-Changes included:
New controller: ActiveCollectionController.java
Test case : ActivateCollectionControllerTest.java

Existing classes changed: JpaCollection.java
JpaCollectionDao.java
CollectionDao.java
CollectionDTO.java

Issues link: #196
#219

### CODE REVIEW

**Comment by anitha181992** [comment]
@ankur-1989 : All the comments received in the pull request https://github.com/ABenchM/abm/pull/296, has been addressed in this pull request.

**Comment by ankur-1989** [comment]
actually frontend code written in this PR -  https://github.com/ABenchM/abm-frontend/pull/258
is not able to handle the exception. I think even if you return null frontend code will throw error. there also we need to handle it.

**Comment by vishaljcj** [comment]
@ankur-1989 could you please mention the scenario in which this error can be reproduced in the front-end.

**Comment by ankur-1989** [comment]
I am not able to open the managepubliccollections page itself.
Apart from this when I open the Publiccollections page i get the following error - 
image

this is related to abm-pen-req PR#258  as I am using abm-pen-req branch.

**Comment by vishaljcj** [comment]
@ankur-1989 this is relate to the PR#259 for manage public collections. Please use the ManagePublicCollection branch in the frontend for testing this.

**Comment by ankur-1989** [comment]
Issues are there in ManagePublicCollection also not able to build that branch.

**Comment by vishaljcj** [comment]
@ankur-1989 could you please mention what issues are you exactly facing this branch? could you please share screenshots. Also @Chinmay-92 and I tested this branch on our systems, and it is getting built properly.

**Pull request merged**
