### PR TITLE
Issue #273 solution

### PR DESCRIPTION
**Pull request by mac24079**
---
name: Handle security exception when restarting the server
about: When restarting the server and the user is logged in, we need to care of some security exceptions.
---

**Is your pull request related to an issue? Please describe.**
Yes. Issue #273

### CODE REVIEW

**Comment by anitha181992** [comment]
@mac24079 : Hey Mohit,
I guess this pull request is dependent on the method requireroles() which has not still pushed into the develop branch. So could you only include changes for handling the security exception, but not the login part.
Thanks,
Anitha

**Comment by ankur-1989** [comment]
@mac24079 
Which frontend should i use to test this pull request effectively?
Regards,
Ankur Gupta

**Comment by mac24079** [comment]
Hello @ankur-1989 ,

Please use this front-end **Feat/fix error 403** - https://github.com/ABenchM/abm-frontend/pull/223 . This branch contains the changes you suggested in https://github.com/ABenchM/abm-frontend/issues/212.

Thanks.

**Comment by mac24079** [comment]
> @mac24079 : Hey Mohit,
> I guess this pull request is dependent on the method requireroles() which has not still pushed into the develop branch. So could you only include changes for handling the security exception, but not the login part.
> Thanks,
> Anitha

Hello @anitha181992 ,
Presently I am writing here from my mobile, can you please confirm what are your changes that I pushed to this pull request? else I'll look them later tonight. If there are any I sincerely apollogise for that. 

Also, as suggested by @nguyenLisa , I will comment that part and write your name over there.

Thanks.

**Comment by mac24079** [comment]
Yes, there was a functionality which got copied from @anitha181992 code and in the other pull request the code was already there so removing the already pushed code. Also, resolved merge conflicts occuring in this branch.

New Merge request: https://github.com/ABenchM/abm/pull/280

So, closing this one.

Thanks.

**Pull request closed without merging**
