### PR TITLE
Anitha unlockuser

### PR DESCRIPTION
**Pull request by anitha181992**
@ankur-1989 : Please review the changes
Name: Lock and unlock user
Issue link: https://github.com/ABenchM/abm/issues/166
This PR contains the changes for locking and unlocking the user by UserAdmin.
By the press of the button the database value is set to either 0 or 1.
UnlockUserController.java---->Controller Changes
Test case: UnlockUserControllerTest

### CODE REVIEW

**Comment by anitha181992** [comment]
I verified that the test case fails when the user is only in "RegisteredUser" group because we want to give only "UserAdmin" the permission to lock or unlock the user.
I added the demo to the "UserAdmin" group and tested.

**Comment by anitha181992** [comment]
Could you please attach the log of the error, so that it is easy to trace back, since the test cases are passing in my system

**Comment by ankur-1989** [comment]
Steps to reproduce the error:- 
1.  Create a user with UserAdmin group only. It should only belong to UserAdmin group. 
2. Login with this user.
3. Try to access the user details with this user. 
4. Try to lock or unlock any other user with this user.

I get this 403 forbidden error - 
image

**Comment by anitha181992** [comment]
@ankur-1989 : I got the issue, I was trying to fetch the user details of the login user rather than the one I was trying to lock, I have fixed the issue.

**Comment by ankur-1989** [comment]
Hi,
The test case related to GetUsersList is still getting failed. 
One more thing, Please use the following naming conventions for the respective operations 
put -> update in table 
post ->  New entry in table
delete -> deletion in table 
I can see it is "post" everywhere in the backend as well in frontend for all the operations.
BR,
Ankur

**Comment by ankur-1989** [comment]
Hi, 
Things are working fine now. Are you working on naming conventions?
BR,
Ankur

**Comment by anitha181992** [comment]
The frontend team is working on the required name changes, so once they do it, we will change the name conventions accordingly by the next pull request

**Comment by Chinmay-92** [comment]
@ankur-1989 As discussed, I have already created new issue for naming convention which needs both frontend and Backend Changes
We will push naming conventions as part of next PR(coordinating with frontend related changes).

**Comment by ankur-1989** [comment]
Thanks. I'll merge this request.

**Pull request merged**
