### PR TITLE
Fix for issue 288

### PR DESCRIPTION
**Pull request by anut347**
added column names also in insert statement.
#288
changes in files JpaFilterPinDao.java, JpaCollectionPinDao.java and JdbcRoleDao.java

### CODE REVIEW

**Comment by nguyenLisa** [comment]
Hi, is that related to #290 ? Also, please add a screenshot of the passing test cases.

**Comment by anut347** [comment]
Hi Lisa, these are not from the functionalities we added and no test cases exists for these yet.

**Comment by nguyenLisa** [comment]
I see. Could you add the test cases then? Thanks!

**Comment by ankur-1989** [comment]
@anut347 
Is there anything pending on this PR? Are you writing test cases for this?
Do we need PR 290?  I found that similar to it.

Best Regards,
Ankur Gupta

**Comment by anut347** [comment]
290 was for abmpgdevelop branch.
There's no other changes wrt fix. I'm trying the test cases.

**Comment by ankur-1989** [comment]
@anut347 
Any update on this ?

**Comment by anut347** [comment]
As discussed @anitha181992 will be working on the test cases for this since i was facing difficulties and other milestone 1 functionalities are to be pushed on priority.

**Comment by anut347** [comment]
Closing this pull request as of now since the functionalities for milestone 1 and 2 are on priority.
A new pull request will be created for this after test cases are done.

**Pull request closed without merging**
