### PR TITLE
Change role for user

### PR DESCRIPTION
**Pull request by anitha181992**
Issue : Change role by UserAdmin
Issue link: https://github.com/ABenchM/abm/issues/166
Controller Added: UpdateRoleController
Test case : UpdateRoleControllerTest

The "UserAdmin" can change the role of the user to either "UserAdmin" or "RegisteredUser"

### CODE REVIEW

**Comment by ankur-1989** [comment]
Hi,
Everything is working fine. As we discussed, please correct the naming convention of the method "postRoleupdate" in UpdateRoleController.java file to keep it in sync with existing methods. 

Best Regards,
Ankur Gupta

**Comment by anitha181992** [comment]
@vishaljcj : The method name is changed to putRoleUpdate as per review comments, please update the same in the frontend as well.
@ankur-1989 : Method name changed

**Comment by ankur-1989** [comment]
Hi @anitha181992 ,
you forgot to change in UpdaterolecontrollerTest.java file. Here, you are still calling post request. please check.

**Comment by anitha181992** [comment]
@ankur-1989 :Missed on that. Fixed it

**Pull request merged**
