### PR TITLE
Pull request for Milestone 4 ( reopened PR )

### PR DESCRIPTION
**Pull request by Chinmay-92**
name: Pull request part 1 for Milestone 4 Project migration
about: Removing commits and replacing it with projects structure in all functionalities for milestone 4

List of functionalities contained in this pull request

1. Create new collection with dummy(hardcoded) projects ( instead of commits from crawlers )
2. Add dummy projects to existing collection
3. Delete project from a collection ( for private versions )
4. Derive version: name and derivedFrom parent is stored
5. Backend Changes
6. Same APIs with projects related logic instead of commits

Database Changes
already merged ( new table Project ).

Frontend branch to test this PR with : project_api_integration

### CODE REVIEW

**Comment by ankur-1989** [comment]
@Chinmay-92  Has the migration issue been resolved?

**Comment by Chinmay-92** [comment]
Yes, the migration issue is resolved.

**Comment by ankur-1989** [comment]
this branch has some issues with the login functionality. When I try to login into the application it is giving throwing errors.

**Comment by Chinmay-92** [comment]
@vishaljcj could you please verify once if something is blocking with the login functionality?

**Comment by vishaljcj** [comment]
@Chinmay-92 Its working fine for me. I am able to login successfully.

**Comment by Chinmay-92** [comment]
Hi @ankur-1989 , It should work correctly since we haven't modified anything related to login functionality. Could you please check again and send the screenshot of the error you're facing while logging in?

**Comment by ankur-1989** [comment]
image
image
image

**Comment by ankur-1989** [comment]
@Chinmay-92 
Screenshots attached for the errors that I am getting.

**Pull request merged**
