### PR TITLE
Changes for multiple user login

### PR DESCRIPTION
**Pull request by anitha181992**
Issue Link: https://github.com/ABenchM/abm/issues/185
This is for allowing "RegisteredUser" and "UserAdmin" to login, since we are managing two users.

### CODE REVIEW

**Comment by ankur-1989** [comment]
Hi @anitha181992,

I was looking into this pull request and I have got one query in order to test the functionality-  
1. How should I add the users against these roles? 

I am not sure, but, looking at the code it seems it will not work.

Thanks and Regards,
Ankur Gupta

**Comment by ankur-1989** [comment]
Hi,

Did you add the entries manually in the database in order to test the functionality?
If yes, then I think it won't be a good idea to test the functionality as we have to add those entries in the database through code only.
As I said, I am not sure it will work or not because I did not find how it is going to add a UserAdmin group in the tables. In order to add the user under UserAdmin, two roles will be created one is UserAdmin only and another one is User itself as a child role.

Regards,
Ankur

**Comment by anitha181992** [comment]
Hello Ankur,

I got what you just said.
Actually for creating the user group like “user admin “ or “registered user
“ we did it through the web Console.

We did not manually edit the sql table for it.
We have implemented a functionality where “change role” when an admin
clicks on it, he can either change the role of the user to “Registereduser”
or “useradmin”.

Hope this clarifies:-)

Regards
Anitha

**Comment by ankur-1989** [comment]
Hi,
I am using this frontendpg branch only. Could you please guide me where can I find "Change Role" feature in UI. One more point is I am not able to load the list of users in Manage Users page. It is giving me same error method not found in backend.

Thanks and Regards,
Ankur

**Comment by anitha181992** [comment]
Hello Ankur,
The "change role" feature is in the manage users page.
@anut347 : will be pushing the changes for getall users before the end of the day
This particular PR is only for making a provision for both Registereduser and useradmin to login.
Regards,
Anitha

**Pull request closed without merging**
