### PR TITLE
delete public collection changes

### PR DESCRIPTION
**Pull request by Chinmay-92**

### CODE REVIEW

**Comment by anut347** [comment]
1) Unnecessary reference field added in UserAdminController.java.

2) As discussed, It would be better if we modify the code to accept list of collection id from frontend.

3) Check in the htm button code also for reference

**Comment by anut347** [comment]
Previous review comments not incorporated.
1.Unnecessary reference field added in UserAdminController.java.
2. It would be better if we modify the code to accept list of collection id from frontend.

if we're not handling second point along with this, we need to create another issue for the same.

**Comment by Chinmay-92** [comment]
1. I have removed unused imports 
2. I will create an issue for accepting list of collection id

**Comment by Chinmay-92** [comment]
I have tested and it works fine with 1 collectionId at a time :)

**Pull request merged**
