### PR TITLE
Changes to update password in role properties table

### PR DESCRIPTION
**Pull request by anut347**
Changes to update password in role properties table and also the test cases which were pushed to the develop branch

### CODE REVIEW

**Comment by anitha181992** [comment]
Verified

**Comment by anut347** [comment]
reopening as its not merged

**Comment by anut347** [comment]
@nguyenLisa : Hi Lisa, We're not able to merge this pull request. I can see Anitha and Chinmay both approved these changes but none of us have the 'merge pull request' button enabled.

**Comment by nguyenLisa** [comment]
@anut347 Sorry. Can you merge now?

**Comment by anut347** [comment]
Thank you Lisa. :)

**Pull request merged**
