### PR TITLE
To get all public collections for the Admin manage collection page

### PR DESCRIPTION
**Pull request by anitha181992**
Functionality : To get all the public collections of the users for the UserAdmin
--> We needed an extra controller because for the normal users, only the active public collections will be viewed, but the "UserAdmin" will be able to view all the public collections which are active as well as deactive
Controller added : AdminManageCollectionController.java
Testcase added : AdminManageCollectionControllerTest.java
Issue link: https://github.com/ABenchM/abm/issues/219

### CODE REVIEW

**Comment by nguyenLisa** [comment]
Why do we need two controllers? Is it possible to have one single controller that checks whether the user is an admin or a regular one?

**Comment by ankur-1989** [comment]
@anitha181992 
you have not attached the screenshot of passing test cases and I believe we can do this with collectionController itself. we don't an extra controller.

Best Regards,
Ankur

**Comment by anitha181992** [comment]
The pull request will be handled by @Chinmay,  I have made the respective changes

**Comment by ankur-1989** [comment]
@Chinmay-92 @anitha181992 
Any update on this?

**Comment by anitha181992** [comment]
Hello Ankur, the work is in progress, since the code changes are complex than thought before, so closing this pull request for now, will reopen it as soon as it is completed

**Pull request closed without merging**
